[book]
authors = []
language = "en"
multilingual = false
src = "src"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
no-section-label = true
git-repository-url = "https://github.com/ChristopherPerry6060/tbs-manual"

[output.html.print]
enable = true
page-break = true

[output.html.fold]
enable = true
level = 0
